### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by vojoup** [notwaldorf/tiny-care-terminal#103]
Hi,
i'm getting this error everytime i try to run tiny-care-terminal.

/usr/local/lib/node_modules/tiny-care-terminal/gitbot.js:15
  let allRepos = [];
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tiny-care-terminal/care.js:4:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

nodejs version : v4.2.6
I'm runnig Linux Mint.
Anyways i love this little thingy !

**Comment by subsidel** [comment]
Hey vojoup 
This package requires a node version greater than 6.10.3 [see package.json](https://github.com/notwaldorf/tiny-care-terminal/blob/61b0beb844a65047a3d860da0533afd2c0ef536c/package.json#L9)  
Try updating to a newer version of node and trying again 😃

**Comment by notwaldorf** [comment]
Yup, that's totally the solution!
