### ISSUE TITLE
Installed but Won't Run

### ISSUE THREAD

**Issue by theleewise** [notwaldorf/tiny-care-terminal#121]
Followed all instructions but getting this error when I try to run it:
`/usr/local/lib/node_modules/tiny-care-terminal/gitbot.js:15
  let allRepos = [];
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tiny-care-terminal/care.js:4:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3`

- **Node Version**: 4.4.3
- **tiny-core-terminal version**: 1.3.2
- **Shell**: bash
- **Terminal Program**: Terminal
- **Operating System**: Mac 10.12.6

Thank you!

**Comment by notwaldorf** [comment]
Your node version is pretty old -- if you update that, it should work!

**Comment by theleewise** [comment]
That did the trick. Thanks!
