### ISSUE TITLE
internal/modules/cjs/loader.js:583

### ISSUE THREAD

**Issue by vojoup** [notwaldorf/tiny-care-terminal#154]
Hello !
When tying to start the program this error occurs : 

```
Error: Cannot find module '../build/Release/git.node'                
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)                                                                                                                                                                  
at Function.Module._load (internal/modules/cjs/loader.js:507:25)                                                                                                                                                                             
at Module.require (internal/modules/cjs/loader.js:637:17)                                                                                                                                                                                    
at require (internal/modules/cjs/helpers.js:20:18)                                                                                                                                                                                           
at Object.<anonymous> (/usr/local/lib/node_modules/tiny-care-terminal/node_modules/git-utils/src/git.js:3:22)                                                                                                                               
at Module._compile (internal/modules/cjs/loader.js:689:30)                                                                                                                                                                                   
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)                                                                                                                                                                     
at Module.load (internal/modules/cjs/loader.js:599:32)                                                                                                                                                                                       
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)                                                                                                                                                                                     
at Function.Module._load (internal/modules/cjs/loader.js:530:3)                                                                                                                                                                              
at Module.require (internal/modules/cjs/loader.js:637:17)                                                                                                                                                                                    
at require (internal/modules/cjs/helpers.js:20:18)                                                                                                                                                                                           
at Object.<anonymous> (/usr/local/lib/node_modules/tiny-care-terminal/gitbot.js:7:13)                                                                                                                                                        
at Module._compile (internal/modules/cjs/loader.js:689:30)                                                                                                                                                                                   
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)                                                                                                                                                                     
at Module.load (internal/modules/cjs/loader.js:599:32) 
```

- **Node Version**:  v10.6.0
- **tiny-core-terminal version**: tiny-care-terminal@1.4.1
- **Shell**: bash
- **Operating System**: Windows (Linux subsystem)

Thank you!

**Comment by mojoaxel** [comment]
Do you habe git installed on your system?

**Comment by vojoup** [comment]
Closed this as I stopped using ttc...
