### ISSUE TITLE
Install failed on `node-gyp rebuild`

### ISSUE THREAD

**Issue by socheatsok78** [notwaldorf/tiny-care-terminal#166]
Please include the template below to ensure a more accurate response to your issue.

- **Node Version**: `v12.12.0`
- **tiny-core-terminal version**:  ~~npm info tiny-care-terminal | grep version:~~
- **Shell**: `zsh`
- **Terminal Program**: `iterm`
- **Operating System**: `Mac OSX Catalina`

### Installation output
[2019-11-08T03_11_22_891Z-install.log](https://github.com/notwaldorf/tiny-care-terminal/files/3822850/2019-11-08T03_11_22_891Z-install.log)

### NPM Log
[2019-11-08T03_11_22_891Z-debug.log](https://github.com/notwaldorf/tiny-care-terminal/files/3822849/2019-11-08T03_11_22_891Z-debug.log)

Thank you!

**Comment by Hubbitus** [comment]
I also have that error on Fedora Linux 31:

```
# npm install -g tiny-care-terminal
npm WARN deprecated phantom@0.8.4: This package is no longer maintained
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated node-uuid@1.3.3: Use uuid module instead
/usr/local/bin/tiny-care-terminal -> /usr/local/lib/node_modules/tiny-care-terminal/care.js

> weak@1.0.1 install /usr/local/lib/node_modules/tiny-care-terminal/node_modules/weak
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.13.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/tiny-care-terminal/node_modules/weak/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tiny-care-terminal/node_modules/weak/.node-gyp'
gyp ERR! System Linux 5.3.16-300.fc31.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/tiny-care-terminal/node_modules/weak
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

> git-utils@5.6.2 install /usr/local/lib/node_modules/tiny-care-terminal/node_modules/git-utils
> node-gyp rebuild

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.13.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/tiny-care-terminal/node_modules/git-utils/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tiny-care-terminal/node_modules/git-utils/.node-gyp'
gyp ERR! System Linux 5.3.16-300.fc31.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/tiny-care-terminal/node_modules/git-utils
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules/tiny-care-terminal/node_modules/weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! git-utils@5.6.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-utils@5.6.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-15T22_33_00_124Z-debug.log
```

**Comment by Hubbitus** [comment]
Is there any workarounds for installation? Docker images may be?

**Comment by mojoaxel** [comment]
@Hubbitus It looks you have problems with access-rights on your system.
Please try to install another global package. e.g.: `npm install -g nvm`.
If this also fails you have to look into your node installation.

**Comment by mojoaxel** [comment]
@socheatsok78 Thank you for creating this issue and sorry for the late response! :disappointed: 

It looks like there is a poblems with node versions >10. I'll look into it.

**Comment by mojoaxel** [comment]
@socheatsok78 I have no idea why you have this errors. Maybe you can try again with the newest version!?

**Comment by Hubbitus** [comment]
`nvm` installed instantly:
```
# npm install -g nvm
npm WARN deprecated nvm@0.0.4: This is NOT the correct nvm. Visit http://nvm.sh and use the curl command to install it.
/usr/local/bin/nvm -> /usr/local/lib/node_modules/nvm/bin/nvm
+ nvm@0.0.4
added 1 package from 1 contributor in 1.137s
```

**Comment by mojoaxel** [comment]
> `nvm` installed instantly:

Strange! It looks to me like a permission issue:

```sh
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/tiny-care-terminal/node_modules/weak/.node-gyp'
```

Sorry, I have no idea at the moment!

**Comment by Hubbitus** [comment]
I've run install command as root

**Comment by Hubbitus** [comment]
For me looks strange:
```
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.13.1"
```
Because of run as root:
```# id
uid=0(root) gid=0(root) группы=0(root)
```

**Comment by socheatsok78** [comment]
> @socheatsok78 Thank you for creating this issue and sorry for the late response! 😞
> 
> I'll look into it.

It ok, i'll check if there is a new version and try to install it again.

**Comment by socheatsok78** [comment]
Installation was success on the latest version. But the error with `node-gyp rebuild` still persist with the following log:

```
yarn global v1.21.1
[1/4] 🔍  Resolving packages...
warning tiny-care-terminal > scraperjs > phantom@0.8.4: This package is no longer maintained
warning tiny-care-terminal > scraperjs > phantom > win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
warning tiny-care-terminal > scraperjs > phantom > shoe > sockjs > node-uuid@1.3.3: Use uuid module instead
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "tiny-care-terminal > blessed-contrib > marked-terminal@1.7.0" has incorrect peer dependency "marked@^0.3.3".
[4/4] 🔨  Building fresh packages...
[1/2] ⡀ git-utils
warning Error running install script for optional dependency: "/Users/socheatsok/.config/yarn/global/node_modules/weak: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/socheatsok/.config/yarn/global/node_modules/weak
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@13.6.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at \"/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python\"
gyp http GET https://nodejs.org/download/release/v13.6.0/node-v13.6.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v13.6.0/node-v13.6.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v13.6.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v13.6.0/SHASUMS256.txt
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/usr/local/Cellar/node/13.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/socheatsok/.config/yarn/global/node_modules/weak/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/13.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/socheatsok/Library/Caches/node-gyp/13.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/socheatsok/Library/Caches/node-gyp/13.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/13.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/socheatsok/Library/Caches/node-gyp/13.6.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/socheatsok/.config/yarn/global/node_modules/weak',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/weakref/src/weakref.o
../src/weakref.cc:147:25: error: too few arguments to function call, expected 4, have 3; did you mean 'Nan::Call'?
  globalCallbackDirect->Call(Nan::GetCurrentContext()->Global(), 1, argv);
                        ^~~~
                        Nan::Call
../../nan/nan_maybe_43_inl.h:345:30: note: 'Nan::Call' declared here
inline MaybeLocal<v8::Value> Call(
                             ^
../src/weakref.cc:168:75: error: too few arguments to function call, single argument 'context' was not specified
  Local<Object> proxy = Nan::New<ObjectTemplate>(proxyClass)->NewInstance();
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/socheatsok/Library/Caches/node-gyp/13.6.0/include/node/v8.h:6565:3: note: 'NewInstance' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(Local<Context> context);
  ^
/Users/socheatsok/Library/Caches/node-gyp/13.6.0/include/node/v8config.h:419:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/weakref.cc:223:55: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
  Local<Boolean> rtn = Nan::New<Boolean>(cont->target.IsNearDeath());
                                         ~~~~~~~~~~~~ ^
3 errors generated.
make: *** [Release/obj.target/weakref/src/weakref.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/13.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command \"/usr/local/Cellar/node/13.6.0/bin/node\" \"/usr/local/Cellar/node/13.6.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/socheatsok/.config/yarn/global/node_modules/weak
gyp ERR! node -v v13.6.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok"
success Installed "tiny-care-terminal@1.7.2" with binaries:
      - tiny-care-terminal
✨  Done in 82.81s.
```

I switched from using `NPM` to `Yarn`.

**Comment by Urahara** [comment]
Via `npm` i can't install because of the mentioned errors, but via yarn everything worked for me.

**Comment by Hubbitus** [comment]
With `yarn` it finished ok, but still has intermediate error installing `node-gyp`:
```
make: Entering directory '/root/node_modules/weak/build'
  CXX(target) Release/obj.target/weakref/src/weakref.o
In file included from ../src/weakref.cc:18:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/weakref.cc: In function ‘void {anonymous}::TargetCallback(const Nan::WeakCallbackInfo<{anonymous}::proxy_container>&)’:
../src/weakref.cc:147:73: error: no matching function for call to ‘v8::Function::Call(v8::Local<v8::Object>, int, v8::Local<v8::Value> [1])’
  147 |   globalCallbackDirect->Call(Nan::GetCurrentContext()->Global(), 1, argv);
      |                                                                         ^
In file included from /root/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/weakref.cc:18:
/root/.cache/node-gyp/12.14.1/include/node/v8.h:4193:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)’
 4193 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Call(Local<Context> context,
      |                                           ^~~~
/root/.cache/node-gyp/12.14.1/include/node/v8.h:4193:43: note:   candidate expects 4 arguments, 3 provided
../src/weakref.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Create(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/weakref.cc:168:75: error: no matching function for call to ‘v8::ObjectTemplate::NewInstance()’
  168 |   Local<Object> proxy = Nan::New<ObjectTemplate>(proxyClass)->NewInstance();
      |                                                                           ^
In file included from /root/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/weakref.cc:18:
/root/.cache/node-gyp/12.14.1/include/node/v8.h:6292:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::ObjectTemplate::NewInstance(v8::Local<v8::Context>)’
 6292 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(Local<Context> context);
      |                                            ^~~~~~~~~~~
/root/.cache/node-gyp/12.14.1/include/node/v8.h:6292:44: note:   candidate expects 1 argument, 0 provided
../src/weakref.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::IsNearDeath(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/weakref.cc:223:55: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
  223 |   Local<Boolean> rtn = Nan::New<Boolean>(cont->target.IsNearDeath());
      |                                                       ^~~~~~~~~~~
In file included from ../../nan/nan.h:54,
                 from ../src/weakref.cc:18:
../src/weakref.cc: At global scope:
/root/.cache/node-gyp/12.14.1/include/node/node.h:560:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  560 |       (node::addon_register_func) (regfunc),                          \\\n      |                                           ^
/root/.cache/node-gyp/12.14.1/include/node/node.h:594:3: note: in expansion of macro ‘NODE_MODULE_X’
  594 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/weakref.cc:289:1: note: in expansion of macro ‘NODE_MODULE’
  289 | NODE_MODULE(weakref, Initialize)
      | ^~~~~~~~~~~
In file included from /root/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/weakref.cc:18:
/root/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.cache/node-gyp/12.14.1/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10004 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
In file included from ../../nan/nan.h:2784,
                 from ../src/weakref.cc:18:
../../nan/nan_weak.h: In instantiation of ‘Nan::WeakCallbackInfo<P>::WeakCallbackInfo(Nan::Persistent<v8::Value>*, Nan::WeakCallbackInfo<P>::Callback, void*, void*, void*) [with T = {anonymous}::proxy_container; Nan::WeakCallbackInfo<P>::Callback = void (*)(const Nan::WeakCallbackInfo<{anonymous}::proxy_container>&)]’:
../../nan/nan_weak.h:264:12:   required from ‘void Nan::Persistent<T, M>::SetWeak(P*, typename Nan::WeakCallbackInfo<P>::Callback, Nan::WeakCallbackType) [with P = {anonymous}::proxy_container; T = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>; typename Nan::WeakCallbackInfo<P>::Callback = void (*)(const Nan::WeakCallbackInfo<{anonymous}::proxy_container>&); Nan::WeakCallbackType = v8::WeakCallbackType]’
../src/weakref.cc:174:79:   required from here
../../nan/nan_weak.h:58:16: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class v8::Persistent<v8::Value>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
   58 |     std::memcpy(&persistent_, persistent, sizeof (v8::Persistent<v8::Value>));
      |     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/weakref.cc:18:
/root/.cache/node-gyp/12.14.1/include/node/v8.h:665:35: note: ‘class v8::Persistent<v8::Value>’ declared here
  665 | template <class T, class M> class Persistent : public PersistentBase<T> {
      |                                   ^~~~~~~~~~
/root/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::WeakCallbackInfo<{anonymous}::proxy_container>; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::WeakCallbackInfo<{anonymous}::proxy_container> >&)]’:
../../nan/nan_weak.h:268:35:   required from ‘void Nan::Persistent<T, M>::SetWeak(P*, typename Nan::WeakCallbackInfo<P>::Callback, Nan::WeakCallbackType) [with P = {anonymous}::proxy_container; T = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>; typename Nan::WeakCallbackInfo<P>::Callback = void (*)(const Nan::WeakCallbackInfo<{anonymous}::proxy_container>&); Nan::WeakCallbackType = v8::WeakCallbackType]’
../src/weakref.cc:174:79:   required from here
/root/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::WeakCallbackInfo<{anonymous}::proxy_container> >::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::WeakCallbackInfo<{anonymous}::proxy_container> >&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10004 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [weakref.target.mk:107: Release/obj.target/weakref/src/weakref.o] Error 1
make: Leaving directory '/root/node_modules/weak/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.4.13-201.fc31.x86_64
gyp ERR! command \"/usr/bin/node\" \"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /root/node_modules/weak
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning No license field
success Saved 1 new dependency.
info Direct dependencies
└─ tiny-care-terminal@1.7.2
info All dependencies
└─ tiny-care-terminal@1.7.2
Done in 2.58s.
```
