### ISSUE TITLE
ReferenceError: gitUsername is not defined

### ISSUE THREAD

**Issue by soniCaH** [notwaldorf/tiny-care-terminal#173]
Can't initiate tiny-care-terminal.
I do have a global git username:

```
$ git config --global user.name                                                                                                                                                                                  
Kevin Van Ransbeeck
```

- **Node Version**: `v10.16.3`
- **tiny-core-terminal version**: `tiny-care-terminal@1.7.3 | MIT | deps: 20 | versions: 23`
- **Shell**: `zsh`
- **Terminal Program**: `iterm`
- **Operating System**: `Mac`

```
~ ❯❯❯ tiny-care-terminal
ReferenceError: gitUsername is not defined
    at async.each (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/gitbot.js:62:28)
    at /Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:2159:44
    at eachOfArrayLike (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:505:13)
    at eachOf (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:556:16)
    at awaitable(eachOf) (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:208:32)
    at Object.eachLimit (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:2221:16)
    at Object.awaitable(eachLimit) (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:208:32)
    at Object.getCommitsFromRepos (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/gitbot.js:61:9)
    at gitbot.findGitRepos (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/care.js:180:12)
    at async.each.err (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/gitbot.js:51:5)
    at wrapper (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:273:20)
    at iteratorCallback (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:500:17)
    at /Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:326:20
    at wrapper (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:273:20)
    at iteratorCallback (/Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:500:17)
    at /Users/kevinvanransbeeck/.nvm/versions/node/v10.16.3/lib/node_modules/tiny-care-terminal/node_modules/async/dist/async.js:326:20
```

**Comment by casserlyprogramming** [comment]
2 things to check:
[1] Make sure you have permissions for all folders. I found one that had readonly access
[2] Make sure that you have the user.name set for all repos in that folder. They should take from global but if you have pulled one from a funny place I've seen it override the user.name with blanks.

**Comment by VonKavalier** [comment]
I have the same problem, and I suspect the fact that my folders are under the docker group :confused:

**Comment by paulleephp** [comment]
I believe this commit fixed this issue but I see that this fix was made after version 1.7.3 was released: https://github.com/notwaldorf/tiny-care-terminal/commit/53dbf3ec4bc2ac479f110d7448036d42a430db4e

**Comment by patoncrispy** [comment]
It would be nice to know which repos don't have the username configured and then instead of hard failing it would just produce a warning which the user could then rectify. The misconfigured repo could be ignored, perhaps?

**Comment by Alos** [comment]
I also have this issue

**Comment by mojoaxel** [comment]
Please test with the new version 1.7.4.

**Comment by patoncrispy** [comment]
@mojoaxel it works for me! Thanks! :D

**Comment by Alos** [comment]
Works for me too! Thanks!
