### ISSUE TITLE
TypeError: content.replace is not a function

### ISSUE THREAD

**Issue by fulf** [notwaldorf/tiny-care-terminal#175]
TCT crashes with the error below for when I have any git repos set up

- **Node Version**: `v10.19.0`
- **tiny-core-terminal version**: `1.7.4`
- **Shell**: `zsh`
- **Terminal Program**: `Terminal`
- **Operating System**: `macOS Catalina 10.15.4`

ENV variables
```
export TTC_BOTS='tinycarebot,selfcare_bot,magicrealismbot'
export TTC_SAY_BOX='RANDOM'
export TTC_REPOS='/Users/soringuga/projects'
export TTC_REPOS_DEPTH=1
export TTC_WEATHER='redacted'
export TTC_CELSIUS=true
export TTC_APIKEYS=false
export TTC_UPDATE_INTERVAL=20
export TTC_TERMINAL_TITLE=false
export TTC_POMODORO=20
export TTC_BREAK=5
```

```
TypeError: content.replace is not a function
    at Box.Element.parseContent (/Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/element.js:364:8)
    at Box.Element.render (/Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/element.js:1839:8)
    at /Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/screen.js:738:8
    at Array.forEach (<anonymous>)
    at Screen.render (/Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/screen.js:735:17)
    at Box.<anonymous> (/Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/screen.js:1936:20)
    at Box.EventEmitter._emit (/Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/events.js:94:20)
    at Box.EventEmitter.emit (/Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/events.js:117:12)
    at Program.<anonymous> (/Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/widgets/screen.js:518:16)
    at Program.emit (events.js:198:13)
    at Program._bindMouse (/Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/program.js:703:10)
    at Program.<anonymous> (/Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/program.js:566:10)
    at Program.emit (events.js:198:13)
    at /Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/program.js:418:15
    at Array.forEach (<anonymous>)
    at ReadStream.input.on.input._dataHandler (/Users/soringuga/.nvm/versions/node/v10.19.0/lib/node_modules/tiny-care-terminal/node_modules/blessed/lib/program.js:416:23)
```

**Comment by AlexMorrisonDev** [comment]
Same issue for me!

`# List of accounts to read the last tweet from, comma separated
# The first in the list is read by the party parrot.
export TTC_BOTS='tinycarebot,selfcare_bot,magicrealismbot'

# Use this to have a different animal say a message in the big box.
# See README for details about supported formats.
# Use e.g 'bunny.cow', 'panda.ansi', 'llama' or 'RANDOM'.
export TTC_SAY_BOX='RANDOM'

# List of folders to look into for `git` commits, comma separated.
export TTC_REPOS='~/Repos/trellis-global'

# The max directory-depth to look for git repositories in
# the directories defined with `TTC_REPOS`. Note that the deeper
# the directory depth, the slower the results will be fetched.
export TTC_REPOS_DEPTH=2

# Location/zip code to check the weather for. Both 90210 and "San Francisco, CA"
# _should_ be ok (the zip code doesn't always work -- use a location
# first, if you can). It's using weather.service.msn.com behind the curtains.
export TTC_WEATHER='Buffalo, NY'

# Set to false if you're an imperial lover <3
export TTC_CELSIUS=false

# Unset this if you _don't_ want to use Twitter keys and want to
# use web scraping instead.
export TTC_APIKEYS=false

# Refresh the dashboard every 20 minutes.
export TTC_UPDATE_INTERVAL=20

# Turn off terminal title
export TTC_TERMINAL_TITLE=false

# Default pomodoro is 20 minutes and default break is 5 minutes.
# You can change these defaults like this.
export TTC_POMODORO=25
export TTC_BREAK=10`

**Comment by mojoaxel** [comment]
I have problems to reproduce this. 
Maybe you could try to narrow down the `TTC_REPOS` to one single repository and try to find one that causes the problem. It looks to me like there is an error but it does not gets displayed because of a consequential problems.

Anybody any ideas?

**Comment by AlexMorrisonDev** [comment]
@mojoaxel So I reduced my `TTC_REPOS` to just one and I no longer have that error. Unfortunately, it won't pull any commits. Is there anything I can provide to help you debug this issue?

**Comment by VFabricio** [comment]
I have the same problem. An exception is being thrown by Blessed at Box.Element.parseContent and it is not handled anywhere. Based on a very quick investigation, this seems to happen for me whenever TTC_REPOS is not empty. I will try to follow the stack trace and see if I find the origin of the problem.

**Comment by irae** [comment]
I believe some dependency that was not pinned broke, since installing old versions does not fix anything, I can't make it work with any revision from the past 2 years.
