### ISSUE TITLE
Unhandled 'error' event when spawning from Ubuntu (17.04)

### ISSUE THREAD

**Issue by aleksandar-todorovic** [notwaldorf/tiny-care-terminal#55]
**Node Version**: `v4.7.2`
**tiny-core-terminal version**: `1.0.8`
**Shell**: `zsh`
**Terminal Program**: `gnome-terminal, terminator`
**Operating System**: `Ubuntu GNOME 17.04`

So, did everything from the setup, exported things to my `.zshrc` file. Trying to execute `tiny-care-terminal` from the command line gives me the following:

```
Error: spawn sh /usr/local/lib/node_modules/tiny-care-terminal/standup-helper.sh ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
    at onErrorNT (internal/child_process.js:355:16)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:990:3
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh /usr/local/lib/node_modules/tiny-care-terminal/standup-helper.sh ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
    at onErrorNT (internal/child_process.js:355:16)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)
```

EDIT: Forgot to add, used Twitter scraping instead of the API keys, and used the default Twitter profiles.

**Comment by chrisgreg** [comment]
Got the same thing on macOS Sierra using Hyper terminal and zshrc.
Using twitter API Keys

**Comment by Garbee** [comment]
Duplicate of #41

**Comment by aleksandar-todorovic** [comment]
You're right, closing this in favor of #41.
