### ISSUE TITLE
Installation failed on Windows 7

### ISSUE THREAD

**Issue by vdubus** [notwaldorf/tiny-care-terminal#77]
Hello, I tried to install tiny-care-terminal using NPM, but it failed on all mine available console.
Not sure if I can try something else.

- **Node Version**: `v7.9.0`
- **Python version**: `Python 3.6.1`
- **PYTHON env**: `C:\Users\vdubus\AppData\Local\Programs\Python\Python36-32\python.exe`
- **PYTHONPATH env**: `C:\Users\vdubus\AppData\Local\Programs\Python\Python36-32`
- **tiny-core-terminal version**: `version: '1.1.1'`
- **Shell**: `bash`
- **Terminal Program**: `cygwin`, `cmd` and `powershell`
- **Operating System**: `Windows 7 Enterprise Service Pack 1 64bits`

Here the result of the command `npm install -g git-standup`:

```
$ npm install -g git-standup
C:\Users\vdubus\AppData\Roaming\npm\git-standup -> C:\Users\vdubus\AppData\Roaming\npm\node_modules\git-standup\git-standup
C:\Users\vdubus\AppData\Roaming\npm
`-- git-standup@2.1.8
```

Here the result of the command `npm install -g tiny-care-terminal`:

```
C:\DEV\Applications>npm install -g tiny-care-terminal
npm WARN deprecated phantom@0.8.4: v1 is no longer maintained, please upgrade to v2.0+ as soon possible.
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated node-uuid@1.3.3: Use uuid module instead
C:\Users\vdubus\AppData\Roaming\npm\tiny-care-terminal -> C:\Users\vdubus\AppData\Roaming\npm\node_modules\tiny-care-terminal\care.js

> weak@1.0.1 install C:\Users\vdubus\AppData\Roaming\npm\node_modules\tiny-care-terminal\node_modules\weak
> node-gyp rebuild


C:\Users\vdubus\AppData\Roaming\npm\node_modules\tiny-care-terminal\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\vdubus\AppData\Local\Programs\Python\Python36-32\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\vdubus\AppData\Roaming\npm\node_modules\tiny-care-terminal\node_modules\weak
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
C:\Users\vdubus\AppData\Roaming\npm
+-- UNMET PEER DEPENDENCY git-standup@^2.1.8
`-- tiny-care-terminal@1.1.1

npm WARN tiny-care-terminal@1.1.1 requires a peer of git-standup@^2.1.8 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 (node_modules\tiny-care-terminal\node_modules\weak):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: weak@1.0.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

It seems that it isn't able to pinpoint the PYTHON executable, yet the command `C:\Users\vdubus\AppData\Local\Programs\Python\Python36-32\python.exe --version` to give me the result `Python 3.6.1`...

**Comment by notwaldorf** [comment]
It says that you can set the PYTHON env variable to the right path -- what happens if you do that?

**Comment by vdubus** [comment]
Just like you can see in the first post, I already did so. I also did set the `PYTHONPATH` environment variable. That's why I am reporting this problem.

**Comment by notwaldorf** [comment]
As of version `1.2.0` there's a new way to use the terminal that doesn't involve the bash script. To use that, set the `TTC_GITBOT` environment variable to `gitlog`. This will become the default way in the future, I'm just giving it a bit of time in the wild before switching to it
