### ISSUE TITLE
Path must be a string

### ISSUE THREAD

**Issue by matt60400** [notwaldorf/tiny-care-terminal#90]
HI,

I have any problem when i launch tiny-care-Terminal :

Below, this is the error return by program.
I think that i forget something ...

I copy sample.env to my .bashrc. and environnement variable works when i try echo $TTC_REPOS.

OS: Mac oS

Can you help me ?
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Function.resolve (/usr/local/lib/node_modules/tiny-care-terminal/node_modules/parse-git-config/index.js:114:22)
    at Function.parseSync [as sync] (/usr/local/lib/node_modules/tiny-care-terminal/node_modules/parse-git-config/index.js:79:24)
    at module.exports (/usr/local/lib/node_modules/tiny-care-terminal/node_modules/git-user-name/index.js:12:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/tiny-care-terminal/gitbot.js:1:107)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/tiny-care-terminal/care.js:4:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

**Comment by notwaldorf** [comment]
What does `echo $TTC_REPOS` look like?

**Comment by jessejanderson** [comment]
I'm having the same issue. `echo $TTC_REPOS` gives me `~/Code,~/workspace`

**Comment by jessejanderson** [comment]
Mine says `path.js:28` but everything else in the error looks the same.

**Comment by GIorfindel** [comment]
I had the same issue on my new computer, it turned out that I had forgotten to create my ~/.gitconfig file

**Comment by mojoaxel** [comment]
I'll have a look!

**Comment by jessejanderson** [comment]
@GIorfindel that was it, thanks!

**Comment by farhantahir** [comment]
Not sure why though I'm still facing this error.

**Comment by mojoaxel** [comment]
@farhantahir Which version are you using?
