### ISSUE TITLE
Launching tiny-care-terminal raise error

### ISSUE THREAD

**Issue by lelouedec** [notwaldorf/tiny-care-terminal#93]
- **Node Version**: `4.2.6`
- **tiny-core-terminal version**: `1.2.0:`
- **Shell**: `bash`
- **Terminal Program**: `ubuntu terminal`
- **Operating System**: `linux ubuntu`
hello 
when trying to launch tiny I get the following error : 
```
/usr/local/lib/node_modules/tiny-care-terminal/gitbot.js:15
  let allRepos = [];
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tiny-care-terminal/care.js:4:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```
Any idea why ?

**Comment by lelouedec** [comment]
**UPDATE**
After putting     `"use strict";` on top of the file gitbot.js the error is not anymore. 
now I have : 
```
Error: spawn sh /usr/local/lib/node_modules/tiny-care-terminal/standup-helper.sh ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn sh /usr/local/lib/node_modules/tiny-care-terminal/standup-helper.sh ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by lelouedec** [comment]
**Final update before closing**

> Just closing this thread for futur users if they get the same error and don't want to search for the solution

To make tiny working : add "use strict"; to gitbot.js on the top and set TTC_GITBOT to gitlog in .profile and it should work

**Comment by mojoaxel** [comment]
OR: update node.js > 6.10.3 :wink:

**Comment by lelouedec** [comment]
:+1: I installed node.js using the apt-get of ubuntu, well I will uninstall ubuntu soon then

**Comment by mojoaxel** [comment]
* [update node on ubuntu](https://askubuntu.com/a/548776/380685)
* https://www.npmjs.com/package/n
* https://github.com/creationix/nvm/blob/master/README.md
